# Generated by Django 4.1.3 on 2023-06-02 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="likeState",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
