# Generated by Django 4.1.3 on 2023-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_like_likestate_alter_like_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="likeState",
            new_name="like_state",
        ),
    ]
