# Generated by Django 5.1.5 on 2025-01-20 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='follow_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='following',
            name='user_being_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
