# Generated by Django 5.1.5 on 2025-01-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_following_follow_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='caption',
        ),
    ]
