# Generated by Django 5.1.5 on 2025-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_rename_content_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postimages'),
        ),
    ]
